version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
    - "6379:6379"

  celery:
    build: .
    command: python -m celery -A tasks worker --loglevel=INFO -B
    links:
      - redis
    depends_on:
      - redis
    restart: "on-failure"
